### ISSUE TITLE
New syntax for multiline strings.

### ISSUE THREAD

**Issue by ghost** [vagoff/inison#7]
I think three quotes `"""` is too many, only one is enough. Also let quotes for multiline strings stay alone.

```
description = "
This is line 1.
This is line 2.
This is line 3.
If you really want to place a quote here:
\"
"

content = "\  # Strip whitespace after this backslash. This is a valid comment.
          This sentence \
          continues \
          here.
"
```

**Comment by vagoff** [comment]
''' ... ''' is need for same purpose as """ but without unescaping things

for example, you use """ if you do want \n-s be converted to \x0d-s and ''' if you want to leave \n-s intact, as two characters
